// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnl428WKW_feICTBks4oN1AYiwz83mFJ0',
    appId: '1:123433202251:web:34a52fa384e54bc09693ce',
    messagingSenderId: '123433202251',
    projectId: 'chat-practise-b5b9a',
    authDomain: 'chat-practise-b5b9a.firebaseapp.com',
    storageBucket: 'chat-practise-b5b9a.appspot.com',
    measurementId: 'G-TXSGZWYW05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqIB0x5XrWyr39-VGjCIRsWH1qic3IK0',
    appId: '1:123433202251:android:c479b85fb863e9269693ce',
    messagingSenderId: '123433202251',
    projectId: 'chat-practise-b5b9a',
    storageBucket: 'chat-practise-b5b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsERY5Pkt_56qEUrLOIjJrOTh2iK5GUus',
    appId: '1:123433202251:ios:7114ad87418497ef9693ce',
    messagingSenderId: '123433202251',
    projectId: 'chat-practise-b5b9a',
    storageBucket: 'chat-practise-b5b9a.appspot.com',
    iosBundleId: 'com.example.chatWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsERY5Pkt_56qEUrLOIjJrOTh2iK5GUus',
    appId: '1:123433202251:ios:f54f8ada0603bcc89693ce',
    messagingSenderId: '123433202251',
    projectId: 'chat-practise-b5b9a',
    storageBucket: 'chat-practise-b5b9a.appspot.com',
    iosBundleId: 'com.example.chatWithFirebase.RunnerTests',
  );
}
